"""
Known-issues page diagram functions.
Auto-registered via @kb_diagram decorator at import time.

All functions follow the same fixed layout (validated by the storage_dell
"good examples" already in the repo): W2=103, IV box 3-99, three Layer/
Component/Notes boxes at (3,33)/(36,66)/(69,99), a 5-column sections table
at dividers (22,41,61,80), a physical-infra line, and a 12-entry glossary.
"""
from ._core import (
    kb_diagram, make_helpers, layout,
    row, bTop, bMid, bBot, sections, connector, arrow, title_border, merge,
)

W2 = 103
IV_L, IV_R = 3, 99
B1_L, B1_R = 3, 33
B2_L, B2_R = 36, 66
B3_L, B3_R = 69, 99
M1, M2, M3 = 18, 51, 84
PD1, PD2, PD3, PD4 = 22, 41, 61, 80


# ── Automation ────────────────────────────────────────────────────────────────

@kb_diagram(
    'ki-ansible',
    'docs/automation/ansible/troubleshooting/known-issues.md',
    'Ansible Automation Platform known issues — Controller, Receptor mesh, execution environments',
)
def ki_ansible():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'Ansible Automation Platform'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'AAP — Controller, Execution Environments, Receptor mesh, Event-Driven Ansible')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: SSH · WinRM · Receptor (TCP 27199) · REST API')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: Automation Controller UI / awx-manage CLI')))
    lines.append(R(bMid(IV_L, IV_R, 'Inventory -> Playbook execution -> Receptor mesh -> Execution node -> Target host')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Control plane'), bMid(B2_L, B2_R, 'Automation Controller'), bMid(B3_L, B3_R, 'Job sched. + RBAC'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Execution'), bMid(B2_L, B2_R, 'Execution Environment'), bMid(B3_L, B3_R, 'Container, ansible-runner'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Mesh'), bMid(B2_L, B2_R, 'Receptor'), bMid(B3_L, B3_R, 'Node routing, TCP 27199'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Inventory'), bMid(B2_L, B2_R, 'Dynamic / static'), bMid(B3_L, B3_R, 'AWX inventory plugins'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Credentials'), bMid(B2_L, B2_R, 'Credential store'), bMid(B3_L, B3_R, 'Vault-backed, encrypted'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Controller', 'Job orchestration', 'HTTPS', 'OAuth2/LDAP', 'Cluster-aware'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Execution node', 'Runs playbooks', 'Receptor/SSH', 'Cert (mesh)', 'Isolated EE'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Receptor mesh', 'Node-to-node route', 'TCP 27199', 'mTLS', 'Mesh topology'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Automation Hub', 'Content/collection', 'HTTPS', 'Token', 'Private + Galaxy'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: Controller HA cluster - execution nodes - PostgreSQL DB - target hosts (SSH/WinRM)'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('AAP            = Ansible Automation Platform; Red Hat enterprise suite (Controller+Hub+EDA)'))
    lines.append(txt_row('Controller     = formerly AWX/Tower; orchestrates job templates, schedules, and RBAC'))
    lines.append(txt_row('Exec. Env.     = container bundling Ansible + collections + Python deps for a job run'))
    lines.append(txt_row('Receptor       = mesh networking layer routing work to execution/hop nodes; TCP 27199'))
    lines.append(txt_row('Playbook       = YAML automation script defining tasks and target hosts'))
    lines.append(txt_row('Become         = privilege escalation (sudo/su) used to run tasks as another user'))
    lines.append(txt_row('Inventory      = list of managed hosts; static file or dynamic plugin (cloud, CMDB)'))
    lines.append(txt_row('Credential     = encrypted secret (SSH key, vault pw, API key) stored in Controller'))
    lines.append(txt_row('Job template   = reusable definition: playbook + inventory + credentials + survey'))
    lines.append(txt_row('Automation Hub = private content repository for certified/validated collections'))
    lines.append(txt_row('EDA            = Event-Driven Ansible; reacts to webhooks/alerts, triggers rulebooks'))
    lines.append(txt_row('ansible-vault  = encrypts sensitive variables/files at rest inside playbooks'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


# ── Backup ────────────────────────────────────────────────────────────────────

@kb_diagram(
    'ki-commvault',
    'docs/backup/commvault/troubleshooting/known-issues.md',
    'Commvault known issues — CommServe, MediaAgents, VSA, dedup',
)
def ki_commvault():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'Commvault'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Enterprise backup platform — CommServe orchestration, MediaAgents, client agents')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: NFS/CIFS · DD Boost · iSCSI/FC (block) · HTTPS (web console)')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: CommCell Console / Command Center web UI')))
    lines.append(R(bMid(IV_L, IV_R, 'CommServe schedule -> MediaAgent -> Storage target -> Catalog -> Client restore')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Control'), bMid(B2_L, B2_R, 'CommServe'), bMid(B3_L, B3_R, 'SQL Server-backed catalog'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Data mover'), bMid(B2_L, B2_R, 'MediaAgent'), bMid(B3_L, B3_R, 'Dedup, encryption'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Client'), bMid(B2_L, B2_R, 'iDataAgent'), bMid(B3_L, B3_R, 'App-aware (SQL/Oracle/VSA)'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Storage'), bMid(B2_L, B2_R, 'Disk lib / Data Domain'), bMid(B3_L, B3_R, 'DD Boost integration'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Catalog'), bMid(B2_L, B2_R, 'CommServe DB'), bMid(B3_L, B3_R, 'SQL Server, sized per env'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['CommServe', 'Orchestrate+catlg', 'HTTPS/SQL', 'AD/local', 'Needs HA plan'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['MediaAgent', 'Moves data to disk', 'TCP 8400', 'Cert', 'Dedup DB local'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['VSA', 'VMware/Hyper-V bkp', 'HTTPS vCenter', 'Service acct', 'Agentless'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Web Console', 'Self-svc restore', 'HTTPS', 'SAML/local', 'End-user portal'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: CommServe server(s) - MediaAgent hosts - disk lib/Data Domain - clients'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('CommCell       = entire Commvault env: CommServe + MediaAgents + clients as one unit'))
    lines.append(txt_row('CommServe      = central SQL-backed control plane; scheduling, catalog, licensing'))
    lines.append(txt_row('MediaAgent     = data mover; performs dedup, compression, encryption to storage'))
    lines.append(txt_row('iDataAgent     = per-app agent (SQL, Oracle, file system) for app-aware backup'))
    lines.append(txt_row('VSA            = Virtual Server Agent; agentless VM backup via vCenter API'))
    lines.append(txt_row('DDB            = Deduplication Database; local per MediaAgent, tracks block sigs'))
    lines.append(txt_row('Storage policy = defines retention, copy precedence, and target library'))
    lines.append(txt_row('Subclient      = logical grouping within a client defining what gets backed up'))
    lines.append(txt_row('DD Boost       = client-side dedup protocol integrating MediaAgents with Data Domain'))
    lines.append(txt_row('Aux. copy      = secondary copy job replicating backup data to another target'))
    lines.append(txt_row('Job Controller = console view showing all running/queued/failed jobs'))
    lines.append(txt_row('Synthetic full = full backup built from existing incrementals, no source re-read'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-dr-operations',
    'docs/backup/dr-operations/troubleshooting/known-issues.md',
    'DR operations known issues — failover testing, re-IP, DNS cutover, app sequencing',
)
def ki_dr_operations():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'DR Operations'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Cross-platform DR runbooks — failover testing, re-IP, DNS cutover, app sequencing')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: DNS · replication-specific (SRDF/SnapMirror/Veeam) · AD/LDAP')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: DR runbook documents / SRM or equivalent orchestration')))
    lines.append(R(bMid(IV_L, IV_R, 'Declare DR -> Storage failover -> Network cutover -> App startup -> Validate')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Storage'), bMid(B2_L, B2_R, 'Array/VM replication'), bMid(B3_L, B3_R, 'SRDF, SnapMirror, Veeam'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Network'), bMid(B2_L, B2_R, 'Re-IP / L2 stretch'), bMid(B3_L, B3_R, 'DNS delegation per site'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Identity'), bMid(B2_L, B2_R, 'AD/DNS at DR site'), bMid(B3_L, B3_R, 'Writable DC required'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Sequencing'), bMid(B2_L, B2_R, 'Runbook order'), bMid(B3_L, B3_R, 'DB-mid.ware-app-LB'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Validation'), bMid(B2_L, B2_R, 'Smoke tests'), bMid(B3_L, B3_R, 'App-specific checks'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['DR runbook', 'Documented steps', 'N/A', 'Change appr.', 'Test quarterly'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['DNS cutover', 'Redirect to DR', 'DNS (53)', 'Admin', 'Pre-stage records'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['AD at DR', 'Auth continuity', 'LDAP/Kerberos', 'Domain admin', 'Need writable DC'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['App sequence', 'Ordered startup', 'App-specific', 'Service accts', 'Doc dependencies'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: production site - DR site - WAN/replication link - DR test network'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('RPO            = Recovery Point Objective; max acceptable data loss in time'))
    lines.append(txt_row('RTO            = Recovery Time Objective; max acceptable time to restore service'))
    lines.append(txt_row('Runbook        = step-by-step documented procedure for executing DR failover'))
    lines.append(txt_row('Failover test  = isolated-network DR exercise that does not impact production'))
    lines.append(txt_row('Re-IP          = changing a host IP to match the DR site network'))
    lines.append(txt_row('L2 extension   = stretching a VLAN across sites so DR keeps the same IP space'))
    lines.append(txt_row('Writable DC    = AD domain controller that can process auth, not just RODC'))
    lines.append(txt_row('DNS delegation = authority for a DNS zone handed to the DR site name servers'))
    lines.append(txt_row('CDP            = Continuous Data Protection; near-zero RPO replication'))
    lines.append(txt_row('Reprotect      = re-establishing replication reverse direction after failover'))
    lines.append(txt_row('Dependency map = documented start order required for an app to come up'))
    lines.append(txt_row('Tabletop test  = DR test run as discussion only, without an actual failover'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-netbackup',
    'docs/backup/netbackup/troubleshooting/known-issues.md',
    'Veritas NetBackup known issues — Master/Media servers, policies, AIR',
)
def ki_netbackup():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'Veritas NetBackup'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Enterprise backup — Master/Media servers, policies, NetBackup catalog')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: NDMP · VTL emulation · DD Boost · TCP 1556 (PBX/vnetd)')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: NetBackup Admin Console / OpsCenter / Web UI (10.x)')))
    lines.append(R(bMid(IV_L, IV_R, 'Policy schedule -> Master server -> Media server -> Storage unit -> Client')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Control'), bMid(B2_L, B2_R, 'Master server'), bMid(B3_L, B3_R, 'Catalog (NBDB), policies'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Data mover'), bMid(B2_L, B2_R, 'Media server'), bMid(B3_L, B3_R, 'Writes to storage units'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Client'), bMid(B2_L, B2_R, 'bpcd agent'), bMid(B3_L, B3_R, 'Per-host backup agent'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Storage'), bMid(B2_L, B2_R, 'Storage unit / DD'), bMid(B3_L, B3_R, 'Disk, tape, DD Boost'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Certs'), bMid(B2_L, B2_R, 'Host ID certificates'), bMid(B3_L, B3_R, 'NBU 8.x+ mandatory'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Master server', 'Catalog+schedule', 'TCP 1556', 'Cert (NBU 8+)', 'NBDB Sybase-based'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Media server', 'Data movement', 'TCP 1556', 'Cert', 'Many per master'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['bpcd', 'Client agent', 'TCP 1556', 'Cert', 'Each client runs'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['AIR', 'Auto Img Replic.', 'TCP 1556', 'Cert', 'Cross-domain copy'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: master server - media servers - Data Domain/tape library - clients'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('Master server  = central control plane; owns the catalog and policies'))
    lines.append(txt_row('Media server   = writes backup data to storage units; can combine with master'))
    lines.append(txt_row('NBDB           = NetBackup relational database (Sybase) storing the catalog'))
    lines.append(txt_row('Policy         = defines schedule, client list, and backup type for clients'))
    lines.append(txt_row('Storage unit   = logical target (disk pool, tape, cloud) media servers write to'))
    lines.append(txt_row('bpcd           = NetBackup client daemon listening for backup/restore requests'))
    lines.append(txt_row('vnetd          = NetBackup network daemon; multiplexes traffic over fewer ports'))
    lines.append(txt_row('AIR            = Auto Image Replication; replicates images between NBU domains'))
    lines.append(txt_row('Host ID cert   = NBU 8.x+ mandatory cert authenticating client to master'))
    lines.append(txt_row('DD Boost       = NetBackup-to-Data-Domain dedup offload integration'))
    lines.append(txt_row('Catalog backup = backup of the NBDB itself; critical for full env recovery'))
    lines.append(txt_row('bpps           = command listing active NetBackup processes for triage'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-veeam',
    'docs/backup/veeam/troubleshooting/known-issues.md',
    'Veeam Backup & Replication known issues — VBR server, proxies, repositories, SOBR',
)
def ki_veeam():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'Veeam Backup & Replication'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'VM-centric backup — VBR server, proxies, repositories, scale-out repository')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS (vCenter API) · NBD/SAN/HotAdd transport · TCP 2500-5000')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: Veeam Backup & Replication Console')))
    lines.append(R(bMid(IV_L, IV_R, 'Job schedule -> Proxy snapshot -> Data mover -> Repository -> Restore point')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Control'), bMid(B2_L, B2_R, 'VBR server'), bMid(B3_L, B3_R, 'SQL Server config DB'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Transport'), bMid(B2_L, B2_R, 'Backup proxy'), bMid(B3_L, B3_R, 'NBD/SAN/HotAdd modes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Storage'), bMid(B2_L, B2_R, 'Backup repository'), bMid(B3_L, B3_R, 'Local, SOBR, dedup appl.'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Source'), bMid(B2_L, B2_R, 'vCenter/ESXi'), bMid(B3_L, B3_R, 'VADP snapshot API'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Cloud tier'), bMid(B2_L, B2_R, 'SOBR capacity tier'), bMid(B3_L, B3_R, 'S3/Blob offload'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['VBR server', 'Job orchestration', 'HTTPS', 'AD/local', 'SQL config DB'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Backup proxy', 'Data transport', 'NBD/SAN/HotAdd', 'Cert', 'CPU/RAM for dedup'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Repository', 'Stores backup file', 'SMB/NFS/local', 'Win/Linux auth', 'Per-VM chains'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['SOBR', 'Scale-out repo', 'Internal', 'N/A', 'Tiers to cloud'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: VBR server - proxy VMs/hosts - repository storage - capacity tier'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('VBR            = Veeam Backup & Replication; core product + management server'))
    lines.append(txt_row('Proxy          = component performing data transport from source to repository'))
    lines.append(txt_row('Transport mode = how a proxy reads VM data: Direct SAN, HotAdd, NBD (network)'))
    lines.append(txt_row('Repository     = storage target holding backup files (VBK/VIB) and metadata'))
    lines.append(txt_row('SOBR           = Scale-Out Backup Repository; pools extents + cloud capacity tier'))
    lines.append(txt_row('VADP           = vSphere APIs for Data Protection; snapshot-based VM backup'))
    lines.append(txt_row('Helper appl.   = temp VM used for SAN/HotAdd transport disk attach'))
    lines.append(txt_row('Instant Recov. = boots a VM directly from backup storage via iSCSI presentation'))
    lines.append(txt_row('CBT            = Changed Block Tracking; lets incrementals skip unchanged blocks'))
    lines.append(txt_row('Backup chain   = full + incremental restore points forming one recoverable set'))
    lines.append(txt_row('Capacity tier  = SOBR object-storage extension for offloading older backups'))
    lines.append(txt_row('SureBackup     = automated test-restore job verifying backup recoverability'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-certifications-san',
    'docs/certifications/san/troubleshooting/known-issues.md',
    'SAN certification exam prep known issues — Brocade BCFP, Cisco CCNP DC, Storage+',
)
def ki_certifications_san():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'SAN Certifications'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Exam prep reference — Brocade BCFP, Cisco CCNP DC (SAN), CompTIA Storage+')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols (exam topics): FC-SW · FCoE · iSCSI')))
    lines.append(R(bMid(IV_L, IV_R, 'Resources: Brocade vFOS lab / Cisco dCloud / official study guides')))
    lines.append(R(bMid(IV_L, IV_R, 'Study guide -> Lab practice -> Practice exam -> Official exam -> Renewal')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Topic'), bMid(B2_L, B2_R, 'Resource'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Brocade BCFP'), bMid(B2_L, B2_R, 'vFOS virtual switch'), bMid(B3_L, B3_R, 'Zoning, fabric admin'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Cisco CCNP DC'), bMid(B2_L, B2_R, 'dCloud MDS/DCNM'), bMid(B3_L, B3_R, 'VSAN, IVR, zoning'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Storage+'), bMid(B2_L, B2_R, 'CompTIA self-study'), bMid(B3_L, B3_R, 'Vendor-neutral basics'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Lab access'), bMid(B2_L, B2_R, 'vFOS / GNS3 / dCloud'), bMid(B3_L, B3_R, 'No FC HW needed'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Validation'), bMid(B2_L, B2_R, 'Practice exams'), bMid(B3_L, B3_R, 'Cross-check official docs'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Brocade vFOS', 'Practice fabric OS', 'N/A', 'Free trial', '30-day reset'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Cisco dCloud', 'Hosted MDS/DCNM', 'HTTPS', 'Cisco account', 'Scheduled sessions'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Official guide', 'Exam blueprint', 'N/A', 'Purchase', 'Trust official src'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Practice exam', 'Self-assessment', 'N/A', 'Purchase/free', 'Verify vs official'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: N/A — virtual labs and hosted vendor lab environments only'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('BCFP           = Brocade Certified Fabric Professional; core Brocade SAN cert'))
    lines.append(txt_row('CCNP DC        = Cisco Certified Network Professional, Data Center track'))
    lines.append(txt_row('Storage+       = CompTIA vendor-neutral storage fundamentals certification'))
    lines.append(txt_row('FC-SW          = native Fibre Channel switching protocol (distinct from FCoE)'))
    lines.append(txt_row('FCoE           = Fibre Channel over Ethernet; encapsulates FC frames in Ethernet'))
    lines.append(txt_row('vFOS           = virtual Fabric OS; Brocade OVA for lab practice without hardware'))
    lines.append(txt_row('dCloud         = Cisco free hosted lab environment for DCNM/MDS/ACI practice'))
    lines.append(txt_row('Zoning         = SAN access control restricting which initiators see which targets'))
    lines.append(txt_row('IVR            = Inter-VSAN Routing; Cisco feature for controlled cross-VSAN traffic'))
    lines.append(txt_row('VSAN (Cisco)   = logical fabric partition on one switch (not VMware vSAN)'))
    lines.append(txt_row('Zoneset        = the active collection of zones enforced on a fabric'))
    lines.append(txt_row('cfgsave        = Brocade command persisting config changes across reboots'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-openai',
    'docs/cloud/ai/openai/troubleshooting/known-issues.md',
    'OpenAI API known issues — rate limits, model deprecation, embeddings, batch API',
)
def ki_openai():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'OpenAI API'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Cloud LLM API — chat completions, embeddings, rate-limited per usage tier')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS (TCP 443) to api.openai.com')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: platform.openai.com dashboard / API keys')))
    lines.append(R(bMid(IV_L, IV_R, 'API request -> Rate limit check -> Model inference -> Response -> Billing')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Access'), bMid(B2_L, B2_R, 'API key / org ID'), bMid(B3_L, B3_R, 'Per-project scoping'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Tier'), bMid(B2_L, B2_R, 'Usage tier'), bMid(B3_L, B3_R, 'RPM/TPM scale w/ spend'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Models'), bMid(B2_L, B2_R, 'GPT-4o, GPT-4, etc.'), bMid(B3_L, B3_R, 'Deprecation schedule'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Billing'), bMid(B2_L, B2_R, 'Token-based'), bMid(B3_L, B3_R, 'Prompt+completion tok.'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Status'), bMid(B2_L, B2_R, 'status.openai.com'), bMid(B3_L, B3_R, 'Check before deep debug'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Chat Completions', 'Text generation', 'HTTPS', 'API key', 'Most common'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Embeddings', 'Vector generation', 'HTTPS', 'API key', 'Used for RAG'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Rate headers', 'Quota visibility', 'HTTPS resp.', 'N/A', 'x-ratelimit-*'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Batch API', 'Async bulk req.', 'HTTPS', 'API key', '24h, cheaper'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: N/A — fully managed SaaS API, no customer-operated infrastructure'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('API key        = secret credential authenticating requests to the OpenAI API'))
    lines.append(txt_row('RPM/TPM        = Requests/Tokens Per Minute; the two rate limit dimensions'))
    lines.append(txt_row('Context window = max tokens (prompt+completion) a model can process at once'))
    lines.append(txt_row('Token          = sub-word text unit; billing and limits are measured in tokens'))
    lines.append(txt_row('Tier           = usage tier unlocked by cumulative spend, raises RPM/TPM'))
    lines.append(txt_row('Backoff        = retry strategy doubling wait time after each 429/500'))
    lines.append(txt_row('Deprecation    = OpenAI retires older models on a published schedule'))
    lines.append(txt_row('Embedding      = vector representation of text for semantic search/RAG'))
    lines.append(txt_row('Batch API      = async bulk endpoint, discounted pricing, ~24h SLA'))
    lines.append(txt_row('Function call  = model output structured to invoke a defined tool'))
    lines.append(txt_row('Streaming      = token-by-token response via server-sent events'))
    lines.append(txt_row('Org ID         = organization identifier scoping billing across API keys'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-aws-evs',
    'docs/cloud/aws/evs/troubleshooting/known-issues.md',
    'AWS Elastic VMware Service known issues — VCF on bare metal, AWS control plane',
)
def ki_aws_evs():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'AWS Elastic VMware Service'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'VCF running on AWS bare-metal hosts inside a customer VPC')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS (AWS API) · vSphere/NSX mgmt protocols on EVS hosts')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: AWS Console/CLI (EVS) + vCenter/NSX Manager (VMware layer)')))
    lines.append(R(bMid(IV_L, IV_R, 'AWS API provision -> Bare-metal hosts -> VCF bring-up -> vCenter/NSX')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Control (AWS)'), bMid(B2_L, B2_R, 'EVS service API'), bMid(B3_L, B3_R, 'Bare-metal+VPC provision'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Control (VMw)'), bMid(B2_L, B2_R, 'vCenter / NSX Mgr'), bMid(B3_L, B3_R, 'Runs inside EVS env'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Compute'), bMid(B2_L, B2_R, 'i4i bare-metal hosts'), bMid(B3_L, B3_R, 'Dedicated, not shared'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Network'), bMid(B2_L, B2_R, 'VPC + DX/VPN'), bMid(B3_L, B3_R, 'Connects to on-prem'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Storage'), bMid(B2_L, B2_R, 'vSAN on EVS hosts'), bMid(B3_L, B3_R, 'Same vSAN as on-prem'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['EVS API', 'Cluster lifecycle', 'HTTPS', 'IAM', 'AWS-native control'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['vCenter (EVS)', 'VMware mgmt', 'HTTPS', 'SSO', 'Same as on-prem'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['NSX Mgr (EVS)', 'Net. virtualizatn', 'HTTPS', 'Local/LDAP', 'Same as on-prem'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['DX/VPN', 'Connect to EVS', 'IPsec/private', 'N/A', 'Needed for hybrid'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: AWS i4i.metal hosts in an AWS AZ - customer VPC - Direct Connect/VPN'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('EVS            = Elastic VMware Service; AWS-managed bare-metal hosts running VCF'))
    lines.append(txt_row('i4i.metal      = AWS bare-metal instance type used as EVS host hardware'))
    lines.append(txt_row('VCF            = VMware Cloud Foundation; the SDDC stack EVS deploys on AWS'))
    lines.append(txt_row('VPC            = Virtual Private Cloud; the AWS network EVS hosts live in'))
    lines.append(txt_row('Direct Connect = dedicated private network link from on-prem to AWS'))
    lines.append(txt_row('AWS Health Dash.= service status page; check before assuming a bug'))
    lines.append(txt_row('Bring-up       = initial VCF deployment process onto EVS bare-metal hosts'))
    lines.append(txt_row('Workload domain= VCF logical grouping of clusters for a given purpose'))
    lines.append(txt_row('SDDC Manager   = VCF lifecycle/orchestration component, present on EVS too'))
    lines.append(txt_row('Security group = AWS-level firewall controlling traffic to/from EVS hosts'))
    lines.append(txt_row('vSAN ports     = UDP 12345/12346 used for vSAN traffic between ESXi hosts'))
    lines.append(txt_row('GA (2025)      = EVS reached General Availability in 2025'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-aws',
    'docs/cloud/aws/troubleshooting/known-issues.md',
    'AWS known issues — IAM, EC2, VPC, service limits',
)
def ki_aws():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'AWS — IAM, EC2, Networking'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Core AWS services — EC2, VPC, IAM, S3, RDS; general infra known issues')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS to AWS APIs · per-service data-plane protocols')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: AWS Console / CLI / CloudFormation / Terraform')))
    lines.append(R(bMid(IV_L, IV_R, 'IAM auth -> API request -> Service control plane -> Resource action -> CloudTrail')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Identity'), bMid(B2_L, B2_R, 'IAM role/user'), bMid(B3_L, B3_R, 'Least-privilege policies'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Compute'), bMid(B2_L, B2_R, 'EC2 instance'), bMid(B3_L, B3_R, 'AMI-based, per-AZ'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Network'), bMid(B2_L, B2_R, 'VPC/Subnet/SG'), bMid(B3_L, B3_R, 'L3/L4 segmentation'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Storage'), bMid(B2_L, B2_R, 'S3 / EBS'), bMid(B3_L, B3_R, 'Object vs block'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Governance'), bMid(B2_L, B2_R, 'Service Quotas'), bMid(B3_L, B3_R, 'Per-region, per-service'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['IAM', 'Identity/access', 'HTTPS', 'Policy-based', 'Roles over keys'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['EC2', 'Virtual compute', 'HTTPS/SSH/RDP', 'Key pair/IAM', 'Per-AZ capacity'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['VPC', 'Network isolation', 'N/A', 'Security groups', 'Subnets per AZ'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['CloudTrail', 'API audit log', 'HTTPS', 'IAM read', 'Key for incidents'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: N/A — AWS-managed regions/AZs; customer controls logical resources'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('IAM            = Identity and Access Management; AWS auth/authz service'))
    lines.append(txt_row('Region/AZ      = geographic AWS area / isolated datacenter within it'))
    lines.append(txt_row('SCP            = Service Control Policy; org-level guardrail over IAM'))
    lines.append(txt_row('Security group = stateful virtual firewall attached to ENIs/instances'))
    lines.append(txt_row('NACL           = Network ACL; stateless subnet firewall, evaluated before SG'))
    lines.append(txt_row('Service Quota  = per-account, per-region limit on a resource'))
    lines.append(txt_row('CloudTrail     = audit log of all API calls made against the account'))
    lines.append(txt_row('ENI            = Elastic Network Interface; virtual NIC for EC2 instances'))
    lines.append(txt_row('IMDS           = Instance Metadata Service; how EC2 fetches its IAM creds'))
    lines.append(txt_row('STS            = Security Token Service; issues temp creds for assumed roles'))
    lines.append(txt_row('Capacity resv. = guarantees EC2 capacity in an AZ for an instance type'))
    lines.append(txt_row('Conn. tracking = state table letting existing flows persist after SG change'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-azure',
    'docs/cloud/azure/troubleshooting/known-issues.md',
    'Microsoft Azure known issues — ARM, VM provisioning, networking, Entra ID',
)
def ki_azure():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'Microsoft Azure'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Azure IaaS/PaaS — ARM, VMs, VNet, AKS, Entra ID')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS (Azure Resource Manager API)')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: Azure Portal / az CLI / ARM templates / Bicep')))
    lines.append(R(bMid(IV_L, IV_R, 'ARM template -> Resource Group -> Resource provider -> Deployed resource')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Identity'), bMid(B2_L, B2_R, 'Entra ID (Azure AD)'), bMid(B3_L, B3_R, 'Tenant-wide directory'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Compute'), bMid(B2_L, B2_R, 'Azure VM'), bMid(B3_L, B3_R, 'Scale Sets for HA'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Network'), bMid(B2_L, B2_R, 'VNet/NSG'), bMid(B3_L, B3_R, 'Subnet-level segmentation'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'PaaS'), bMid(B2_L, B2_R, 'AKS / App Service'), bMid(B3_L, B3_R, 'Managed K8s/web hosting'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Governance'), bMid(B2_L, B2_R, 'Subscription/RG'), bMid(B3_L, B3_R, 'Quota+policy boundary'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['ARM', 'Deployment engine', 'HTTPS', 'Entra ID', 'Declarative tmpls'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Entra ID', 'Identity provider', 'HTTPS/SAML', 'Cond. Access', 'Was Azure AD'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['VNet', 'Network isolation', 'N/A', 'NSG rules', 'Peering supported'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['AKS', 'Managed K8s', 'HTTPS', 'Entra ID/RBAC', 'Node pools/wkload'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: N/A — Microsoft-managed regions; customer controls logical resources'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('ARM            = Azure Resource Manager; deployment/management layer'))
    lines.append(txt_row('Resource Group = logical container grouping resources by lifecycle'))
    lines.append(txt_row('Entra ID       = Microsoft identity platform, formerly Azure AD'))
    lines.append(txt_row('Subscription   = billing+access boundary; quotas apply per subscription'))
    lines.append(txt_row('NSG            = Network Security Group; stateful firewall on subnets/NICs'))
    lines.append(txt_row('VNet peering   = private connectivity between two virtual networks'))
    lines.append(txt_row('Managed Identity= Entra ID identity auto-assigned to an Azure resource'))
    lines.append(txt_row('AKS            = Azure Kubernetes Service; managed control plane'))
    lines.append(txt_row('Availability Zone= physically separate datacenter within a region'))
    lines.append(txt_row('Cond. Access   = Entra ID policy enforcing MFA/device compliance'))
    lines.append(txt_row('Service principal= non-human Entra ID identity used by apps/automation'))
    lines.append(txt_row('ACR            = Azure Container Registry; often paired with AKS'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-github-actions',
    'docs/automation/github-actions/troubleshooting/known-issues.md',
    'GitHub Actions known issues — self-hosted runners, secrets, workflow triggers',
)
def ki_github_actions():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'GitHub Actions'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'CI/CD platform — cloud-hosted or self-hosted runners executing workflow YAML')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS (TCP 443) to github.com · webhook callbacks')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: Settings -> Actions (repo/org/enterprise level)')))
    lines.append(R(bMid(IV_L, IV_R, 'Trigger -> Runner pickup -> Job steps -> Artifacts/Logs -> Status check')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Trigger'), bMid(B2_L, B2_R, 'Workflow YAML'), bMid(B3_L, B3_R, 'on: push/PR/schedule'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Compute'), bMid(B2_L, B2_R, 'Hosted / self-hosted runner'), bMid(B3_L, B3_R, 'Labels match runs-on'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Identity'), bMid(B2_L, B2_R, 'GITHUB_TOKEN / OIDC'), bMid(B3_L, B3_R, 'Scoped per job'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Secrets'), bMid(B2_L, B2_R, 'Repo/org/env secrets'), bMid(B3_L, B3_R, 'Masked in logs'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Artifacts'), bMid(B2_L, B2_R, 'actions/upload-artifact'), bMid(B3_L, B3_R, '90-day default retention'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Hosted runner', 'Ephemeral VM/job', 'HTTPS', 'GITHUB_TOKEN', 'GitHub-managed'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Self-hosted runner', 'Customer compute', 'HTTPS out (443)', 'Runner token', 'Long-lived process'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['OIDC', 'Cloud federation', 'HTTPS', 'JWT claims', 'No static keys'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Environments', 'Deploy gating', 'N/A', 'Reviewers', 'Protection rules'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: GitHub-hosted VM fleet (cloud) or customer-owned self-hosted runner hosts'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('Workflow       = YAML file in .github/workflows defining triggers, jobs, and steps'))
    lines.append(txt_row('Runner         = the machine (hosted or self-hosted) that executes a job'))
    lines.append(txt_row('runs-on        = label selecting which runner picks up a job (e.g. ubuntu-latest)'))
    lines.append(txt_row('GITHUB_TOKEN   = auto-generated per-job token scoped to the triggering repository'))
    lines.append(txt_row('OIDC           = OpenID Connect; lets workflows get short-lived cloud creds, no secrets'))
    lines.append(txt_row('Secret         = encrypted value set at repo/org/environment scope, masked in logs'))
    lines.append(txt_row('Environment    = named deployment target with optional required reviewers/wait timer'))
    lines.append(txt_row('Artifact       = file(s) uploaded by a job for later jobs or download, time-limited'))
    lines.append(txt_row('Matrix build   = one job definition fanned out across a grid of input variables'))
    lines.append(txt_row('Self-hosted    = customer-managed runner; needs outbound 443 to github.com, no inbound'))
    lines.append(txt_row('Concurrency    = group key limiting/cancelling overlapping workflow runs'))
    lines.append(txt_row('Reusable wflow = workflow called by another workflow via workflow_call'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-powershell',
    'docs/automation/powershell/troubleshooting/known-issues.md',
    'PowerShell / WinRM known issues — remoting, execution policy, module loading',
)
def ki_powershell():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'PowerShell / WinRM'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'PowerShell 5.1 (Windows-only) and 7.x (cross-platform) scripting and remoting')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: WinRM (HTTP 5985 / HTTPS 5986) · SSH (PS 7.x remoting)')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: PowerShell console / ISE / VS Code extension')))
    lines.append(R(bMid(IV_L, IV_R, 'Script -> Execution policy check -> Module import -> Remoting session -> Target')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Engine'), bMid(B2_L, B2_R, 'PS 5.1 / PS 7.x (Core)'), bMid(B3_L, B3_R, '.NET Framework / .NET'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Remoting'), bMid(B2_L, B2_R, 'WinRM listener'), bMid(B3_L, B3_R, 'HTTP 5985 / HTTPS 5986'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Security'), bMid(B2_L, B2_R, 'Execution policy'), bMid(B3_L, B3_R, 'Restricted/RemoteSigned'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Modules'), bMid(B2_L, B2_R, 'PSGallery / PSRepository'), bMid(B3_L, B3_R, 'Per-user or system scope'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Delegation'), bMid(B2_L, B2_R, 'CredSSP / Kerberos'), bMid(B3_L, B3_R, 'Double-hop auth'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Enter-PSSession', 'Interactive remote', 'WinRM', 'Kerberos/NTLM', 'Single host'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Invoke-Command', 'Batch remoting', 'WinRM', 'Kerberos/NTLM', 'Fan-out to many'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['CredSSP', 'Cred. delegation', 'WinRM', 'Delegated creds', 'Double-hop fix'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['PSGallery', 'Module source', 'HTTPS', 'API key (publish)', 'Public repo'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: Windows hosts (WinRM listener) - Linux/macOS hosts (PS 7.x + SSH remoting)'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('WinRM          = Windows Remote Management; SOAP-based remoting over HTTP/HTTPS'))
    lines.append(txt_row('Execution pol. = local script-running policy: Restricted/AllSigned/RemoteSigned/etc.'))
    lines.append(txt_row('TrustedHosts   = client allow-list of remote hosts permitted without Kerberos'))
    lines.append(txt_row('CredSSP        = Credential Security Support Provider; enables credential delegation'))
    lines.append(txt_row('Double-hop     = a remote session needing to authenticate onward to a third host'))
    lines.append(txt_row('PSGallery      = Microsoft-hosted public PowerShell module repository'))
    lines.append(txt_row('Zone.Identifier= NTFS alternate stream marking a file as downloaded from the internet'))
    lines.append(txt_row('Unblock-File   = removes the Zone.Identifier stream so a script will run'))
    lines.append(txt_row('PSSession      = a persistent remoting connection reusable across multiple commands'))
    lines.append(txt_row('Desired State Config. = DSC; declarative configuration management built into PS'))
    lines.append(txt_row('$PSVersionTable= built-in variable reporting PS edition, version, and OS platform'))
    lines.append(txt_row('Constrained EP = endpoint exposing only a restricted command set for remoting'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-python-automation',
    'docs/automation/python/troubleshooting/known-issues.md',
    'Python automation scripts known issues — venvs, SSL trust, REST API integration',
)
def ki_python_automation():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'Python Automation Scripts'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Python 3.10/3.12 scripts for infrastructure automation and REST API integration')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS (requests/urllib3) · SSH (paramiko/fabric) · SNMP (pysnmp)')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: venv per project / pip / requirements.txt or pyproject.toml')))
    lines.append(R(bMid(IV_L, IV_R, 'venv activate -> pip install -> script run -> API/SSH call -> target system')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Isolation'), bMid(B2_L, B2_R, 'venv / virtualenv'), bMid(B3_L, B3_R, 'Per-project deps'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Packages'), bMid(B2_L, B2_R, 'pip / PyPI'), bMid(B3_L, B3_R, 'requirements.txt pin'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Trust'), bMid(B2_L, B2_R, 'CA bundle / certifi'), bMid(B3_L, B3_R, 'Internal CA often missing'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'HTTP client'), bMid(B2_L, B2_R, 'requests / httpx'), bMid(B3_L, B3_R, 'Timeout, retries'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Remote exec'), bMid(B2_L, B2_R, 'paramiko / fabric'), bMid(B3_L, B3_R, 'SSH key or password'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['requests', 'REST API calls', 'HTTPS', 'Bearer/Basic/cert', 'Uses OS trust'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['paramiko', 'SSH automation', 'SSH', 'Key/password', 'Pure-Python SSH2'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['venv', 'Dep. isolation', 'N/A', 'N/A', 'One per project'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['pip', 'Package install', 'HTTPS to PyPI', 'Token (priv idx)', 'Pin versions'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: automation/jump host running scripts - target APIs/SSH endpoints over network'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('venv           = isolated Python environment with its own interpreter + package set'))
    lines.append(txt_row('pip            = Python package installer; reads requirements.txt or pyproject.toml'))
    lines.append(txt_row('certifi        = Python package bundling Mozilla CA certs used as a trust fallback'))
    lines.append(txt_row('SSLCertVerif.  = error raised when a server cert chain is not in the trust store'))
    lines.append(txt_row('requests       = most common Python HTTP client library for REST automation'))
    lines.append(txt_row('paramiko       = pure-Python SSHv2 library used for remote command execution'))
    lines.append(txt_row('Timeout        = max wait for a connect/read; unset defaults can hang indefinitely'))
    lines.append(txt_row('update-ca-trust= RHEL command to add a CA cert to the OS-wide trust store'))
    lines.append(txt_row('site-packages  = directory where pip installs packages for an interpreter/venv'))
    lines.append(txt_row('JSONDecodeError= raised when a response body is not valid JSON (often an HTML error page)'))
    lines.append(txt_row('Distributed Seg. Proc. = backup-specific DSP; unrelated term seen in some integration logs'))
    lines.append(txt_row('Idempotency    = property where re-running a script produces the same end state safely'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines


@kb_diagram(
    'ki-terraform',
    'docs/automation/terraform/troubleshooting/known-issues.md',
    'Terraform / OpenTofu known issues — state locking, providers, Terraform Enterprise',
)
def ki_terraform():
    R, txt_row = make_helpers(W2)
    lines = []
    lines.append(title_border(W2, 'Terraform / OpenTofu'))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(bMid(IV_L, IV_R, 'Infrastructure-as-code: declarative state-driven provisioning via providers')))
    lines.append(R(bMid(IV_L, IV_R, 'Protocols: HTTPS to provider APIs · HTTPS to remote state backend (S3/TFE)')))
    lines.append(R(bMid(IV_L, IV_R, 'Management: terraform CLI / Terraform Enterprise (TFE) UI')))
    lines.append(R(bMid(IV_L, IV_R, 'plan -> diff against state -> apply -> provider API calls -> state updated')))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(merge(bTop(B1_L, B1_R), bTop(B2_L, B2_R), bTop(B3_L, B3_R))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Layer'), bMid(B2_L, B2_R, 'Component'), bMid(B3_L, B3_R, 'Notes'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'State'), bMid(B2_L, B2_R, 'State file + lock'), bMid(B3_L, B3_R, 'S3/TFE/Consul backend'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Providers'), bMid(B2_L, B2_R, 'AWS/Azure/vSphere etc.'), bMid(B3_L, B3_R, 'Plugin binaries'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Execution'), bMid(B2_L, B2_R, 'CLI / TFE agent'), bMid(B3_L, B3_R, 'Local or remote runs'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Modules'), bMid(B2_L, B2_R, 'Registry / Git source'), bMid(B3_L, B3_R, 'Reusable IaC units'))))
    lines.append(R(merge(bMid(B1_L, B1_R, 'Workspace'), bMid(B2_L, B2_R, 'TFE workspace'), bMid(B3_L, B3_R, 'Per-environment state'))))
    lines.append(R(merge(bBot(B1_L, B1_R), bBot(B2_L, B2_R), bBot(B3_L, B3_R))))
    lines.append(txt_row())
    lines.append(R(arrow([M1, M2, M3])))
    lines.append(txt_row())
    lines.append(R(bTop(IV_L, IV_R)))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Component', 'Purpose', 'Protocol', 'Auth', 'Notes'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['State backend', 'Stores tfstate', 'HTTPS', 'IAM/Token', 'Lock vs. races'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Provider plugin', 'API translation', 'Provider-specific', 'Cloud creds', 'Versioned, cached'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['TFE agent', 'Remote execution', 'HTTPS to TFE', 'Agent token', 'On-prem access'])))
    lines.append(R(sections(IV_L, IV_R, [PD1, PD2, PD3, PD4], ['Module registry', 'Shared IaC modules', 'HTTPS/Git', 'Token (priv reg)', 'Public + private'])))
    lines.append(R(bBot(IV_L, IV_R)))
    lines.append(txt_row())
    lines.append(txt_row('Physical: CLI/agent host running terraform - state backend - target cloud/on-prem APIs'))
    lines.append(txt_row())
    lines.append(txt_row('Key terms:'))
    lines.append(txt_row())
    lines.append(txt_row('State file     = JSON record mapping resources to real infrastructure IDs'))
    lines.append(txt_row('State lock     = prevents two concurrent applies from corrupting the same state'))
    lines.append(txt_row('Provider       = plugin translating HCL resources into API calls for a platform'))
    lines.append(txt_row('Plan           = dry-run diff between desired config and current state'))
    lines.append(txt_row('Apply          = executes the plan, calling provider APIs to reach desired state'))
    lines.append(txt_row('Drift          = real infrastructure diverges from what state file records'))
    lines.append(txt_row('Module         = reusable bundle of resources with input variables and outputs'))
    lines.append(txt_row('TFE            = Terraform Enterprise; self-hosted remote run/state platform'))
    lines.append(txt_row('Workspace      = isolated state + variable set, typically one per environment'))
    lines.append(txt_row('Agent pool     = group of self-hosted runners executing TFE runs in private networks'))
    lines.append(txt_row('Parallelism    = max concurrent resource operations per apply (default 10)'))
    lines.append(txt_row('force-unlock   = manually clears a stuck state lock after confirming no other run'))
    lines.append(txt_row())
    lines.append('└' + '─' * W2 + '┘')
    return lines
