#!/usr/bin/env python3
"""
remove_hexagon_d2.py — Remove trivial hub-and-spoke D2 blocks that contain
{shape: hexagon} from all markdown files in docs/.

These were auto-generated by mass_diagram_gen.py and now render via Kroki
as tiny confusing mini-diagrams on every page. Only blocks containing the
hexagon shape are removed; all other D2 blocks are preserved.
"""

import re
from pathlib import Path

ROOT = Path(__file__).parent.parent / "docs"

D2_BLOCK = re.compile(r"```d2\n.*?\n```", re.DOTALL)


def is_hexagon_block(block: str) -> bool:
    return "{shape: hexagon}" in block


def process(text: str) -> tuple[str, int]:
    removed = 0

    def replace(m):
        nonlocal removed
        if is_hexagon_block(m.group(0)):
            removed += 1
            return ""
        return m.group(0)

    new_text = D2_BLOCK.sub(replace, text)
    new_text = re.sub(r"\n{3,}", "\n\n", new_text)
    return new_text, removed


def main():
    paths = sorted(ROOT.rglob("*.md"))
    total_files = total_removed = 0

    for path in paths:
        text = path.read_text(encoding="utf-8")
        if "{shape: hexagon}" not in text:
            continue
        new_text, count = process(text)
        if count > 0:
            path.write_text(new_text, encoding="utf-8")
            total_files += 1
            total_removed += count

    print(f"Done: {total_removed} blocks removed from {total_files} files")


if __name__ == "__main__":
    main()
